name: "Boyacars"
tagline: "Location de Voitures à Marrakech"
description: "Location de voiture économique à Marrakech"
url: "https://boyacars.com"
logo: "/assets/images/logos/logo-dark.png"
logo_light: "/assets/images/logos/logo-light.png"

contact:
  email: "support@boyacars.com"
  email_display: "support@boyacars.com"
  phone: "(+212) 662-825804"
  phone_raw: "+212662825804"
  whatsapp: "+212662825804"
  address: "Bd Allal Al Fassi, Marrakech 40000, Marrakech, Maroc"

social:
  - name: whatsapp
    url: "https://wa.me/212662825804"
    icon: "fa-brands fa-whatsapp"

colors:
  primary: "#10B981"
